export const REGISTER_USER = 'REGISTER_USER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_ERROR = 'REGISTER_ERROR';

export const REGISTER_SUMBITTABLE = 'REGISTER_SUBMITTABLE';

export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';

export const SOCIAL_LOGIN_ERROR = 'SOCIAL_LOGIN_ERROR';
