export const REGISTER_USER = 'REGISTER_USER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_ERROR = 'REGISTER_ERROR';

export const REGISTER_SUMBITTABLE = 'REGISTER_SUBMITTABLE';

export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';

export const SOCIAL_LOGIN_ERROR = 'SOCIAL_LOGIN_ERROR';

export const FETCH_FOLLOWING = 'FETCH_FOLLOWING';

export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';

export const FOLLOW_USER = 'FOLLOW_USER';

export const UNFOLLOW_USER = 'UNFOLLOW_USER';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const COMMENT_ON_ARTICLE = 'COMMENT_ON_ARTICLE';

export const COMMENT_ON_COMMENT = 'COMMENT_ON_COMMENT';

export const EDIT_COMMENT = 'EDIT_COMMENT';

export const LOCAL_STORAGE = 'LOCAL_STORAGE';
